name: On-demand self-hosted AWS EC2 runner for GitHub Actions
description: GitHub Action for automatic creation and registration AWS EC2 instance as a GitHub Actions self-hosted runner.
author: Volodymyr Machula
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used to remove the runner from GitHub when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  aws-resource-tags:
    description: >-
      Tags to attach to the launched EC2 instance and volume.
      This must be a stringified array of AWS Tag objects, with both Key and Value fields,
      for example: '[{"Key": "TagKey1", "Value": "TagValue1"}, {"Key": "TagKey2", "Value": "TagValue2"}]'
    required: false
    default: '[]'
  runner-home-dir:
    description: >-
      Directory that contains actions-runner software and scripts. E.g. /home/runner/actions-runner.
    required: false
  ec2-launch-params:
    description: >-
      EC2 launch params. See https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#runInstances-property for all possible properties.
    required: false
outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
runs:
  using: node12
  main: ./dist/index.js
