name: (PR) Automations

on:
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    uses: ./.github/workflows/shared-lint-code.yml

  #package-distribution-files:
  #  uses: ./.github/workflows/shared-package-distribution-files.yml
