name: PR automations
on:
  pull_request:
    branches:
      - main
jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ec2-github-runner-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
