name: PR automations
on:
  pull_request:
    branches:
      - main
jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ec2-github-runner-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
  package:
    name: Package distribution files
    runs-on: ubuntu-latest
    needs:
      - lint-code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ec2-github-runner-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm install
      - name: Package
        run: npm run package
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Update dist" || echo "No changes to commit"
          git push origin ${{ github.head_ref }}
